services:
  postgres:
    image: 'postgres:16'
    hostname: postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  mailpit:
    image: axllent/mailpit:latest
    hostname: mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
  server:
    hostname: server
    image: mszajner/beanguard-server:0.1-latest
    depends_on:
      - postgres
      - mailpit
    env_file: .env
    ports:
      - "8000:80"
  shop:
    hostname: shop
    image: mszajner/beanguard-shop:0.1-latest
    depends_on:
      - server
    env_file: .env
    environment:
      NODE_ENV: 'development'
    ports:
      - "8001:80"
  admin:
    hostname: admin
    image: mszajner/beanguard-admin:0.1-latest
    depends_on:
      - server
    env_file: .env
    environment:
      NODE_ENV: 'development'
    ports:
      - "8002:80"
#  demo:
#    hostname: demo
#    build:
#      context: .
#    env_file: .env
#    ports:
#      - "8090:8090"

volumes:
  postgres_data:
